USE YnovShop;

CREATE TABLE y_user(
	Id INT IDENTITY NOT NULL,
	Firstname VARCHAR(50) NOT NULL,
	Lastname VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	PasswordHash VARCHAR(200) NOT NULL,
	Salt VARCHAR(200) NOT NULL,
	Registration DATETIME2 NOT NULL,
	IsEnable BIT DEFAULT 0 NOT NULL,
	CONSTRAINT PK_USER PRIMARY KEY(Id));
GO

CREATE TABLE y_category(
	Id INT IDENTITY NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Description VARCHAR(200) NOT NULL,
	CONSTRAINT PK_CATEGORY PRIMARY KEY(Id));
GO

CREATE TABLE y_manufacturer(
	Id INT IDENTITY NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Logo TEXT NOT NULL,
	CONSTRAINT PK_MANUFACTURER PRIMARY KEY(Id));
GO

CREATE TABLE y_product(
	Id INT IDENTITY NOT NULL,
	IdCategory INT NOT NULL,
	IdManufacturer INT NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Description TEXT NOT NULL,
	Price FLOAT NOT NULL,
	Quantity INT NOT NULL,
	CONSTRAINT PK_PRODUCT PRIMARY KEY(Id),
	CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (IdCategory) REFERENCES y_category(id),
	CONSTRAINT FK_PRODUCT_MANUFACTURER FOREIGN KEY (IdManufacturer) REFERENCES y_manufacturer(id));
GO

