USE YnovShop;

CREATE TABLE y_user(
	Id INT IDENTITY NOT NULL,
	Firstname VARCHAR(50) NOT NULL,
	Lastname VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	PasswordHash VARCHAR(200) NOT NULL,
	Salt VARCHAR(200) NOT NULL,
	Registration DATETIME2 NOT NULL,
	IsEnable BIT DEFAULT 0 NOT NULL,
	CONSTRAINT PK_USER PRIMARY KEY(Id));
GO
